config/routes.rb
Charity::Application.routes.draw do
  resources :pages, only: [:index, :new, :edit, :create, :update, :destroy]

  root :to => "home#index"

  devise_for :users

  get '/:id' => 'public_pages#show'

end

app/models/page.rb
class Page < ActiveRecord::Base
  include Sluggable
  slug_from :name

  has_and_belongs_to_many :users

  before_validation :generate_slug

  has_attached_file :image,
    :storage => :s3,
    :bucket => 'charity.heroku.com',
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
      stored_location_for(resource) || pages_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = Page.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!

  # GET /pages
  # GET /pages.json
  def index
    @pages = current_user.pages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = current_user.pages.new(params[:page])

    respond_to do |format|
      if current_user.save
        format.html { redirect_to pages_path, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to pages_path, notice: 'Page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  # GET /page_slug
  def show
    @page = Page.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @page }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%p
  This app allows charities to create #{link_to 'QR codes', '#divModalDialog1'} that are linked to a #{link_to 'donation page', '#divModalDialog2'}.

%h2 Newest Charities
- @pages.each do |page|
  = link_to page.name, "/#{page.slug}", class: 'button'

#divModalDialog1.divModalDialog
  %div
    %h1 Leave this app and read about QR codes?
    %ul
      %li
        %a{:href => "http://en.wikipedia.org/wiki/QR_code"} Go to Wikipedia!
      %li
        %a{:href => "#"} Not right now

#divModalDialog2.divModalDialog
  %div
    %h1 Leave this app and read about Google Checkout?
    %ul
      %li
        %a{:href => "https://checkout.google.com/seller/npo/"} Go to Google!
      %li
        %a{:href => "#"} Not right now

app/views/layouts/application.html.haml
!!!
= render "layouts/application/html_tag"
%head
  %meta{:charset => "utf-8"}
  = csrf_meta_tag
  /
    Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess
  %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
  %title Charity
  %meta{:content => "", :name => "description"}
  %meta{:content => "", :name => "author"}
  / Mobile viewport optimized: j.mp/bplateviewport
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  / Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons
  / CSS: implied media="all"
  = stylesheet_link_tag :application
  = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Spinnaker"
  / More ideas for your <head> here: h5bp.com/docs/#head-Tips
  = javascript_include_tag :application
%body
  = render "layouts/application/header"
  #main.wrapper
    - if notice
      #flash_notice.notice= notice
    - if alert
      #flash_alert.alert= alert
    %article
      %header
        = yield
  #footer-container.noise
    %footer.wrapper
      %h3
        Designed and built for
        = link_to 'Google HTML5 Hackathon', 'http://webapphackmtl.eventbrite.com/'
  :javascript
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/layouts/application/_header.html.haml
#header-container.noise
  %header.wrapper
    %h1#title
      = link_to 'Charity Donations', '/'
    %nav
      %ul
        = render 'shared/navigation'

app/views/layouts/application/_html_tag.html.erb
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

app/views/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  %p.field
    = f.label :name, "What's your charity called?"
    %br/
    = f.text_field :name
  %p.field
    = f.label :google_checkout_merchant_id, "We'll need your"
    = link_to 'Google Checkout ID', '#divModalDialog1'
    %br/
    = f.text_field :google_checkout_merchant_id
  %p.field
    = f.label :image, 'Use a custom background image?'
    %br/
    = f.file_field :image
    %p
      Current image:
      = image_tag @page.image.url
  %p.actions
    = f.submit 'Save'
  %p.cancel
    = link_to 'Back', pages_path

#divModalDialog1.divModalDialog
  %div
    %h1 Leave this app and read about Google Checkout?
    %ul
      %li
        %a{:href => "https://checkout.google.com/seller/npo/"} Go to Google!
      %li
        %a{:href => "#"} Not right now

app/views/pages/edit.html.haml
%h2 Editing page
.charity
  = render 'form'

app/views/pages/index.html.haml
#charities
  %h2 Charity Pages
  #new-charity= link_to 'New', new_page_path, class: 'button'
  - @pages.each do |page|
    .charity
      %h3= link_to page.name, "/#{page.slug}"
      = link_to 'Edit', edit_page_path(page), class: 'button'
      = link_to 'Delete', page, :confirm => 'Are you sure?', :method => :delete, class: 'button'
      != '<div class="page_qr page_qr_'+page.slug+'"></div>'
      :javascript
        $(function() {
          $('#{".page_qr_"+page.slug}').qrcode("#{request.protocol}#{request.host}:#{request.port}/#{page.slug}");
        });

app/views/pages/new.html.haml
%h2 Create a new charity page
.charity
  = render 'form'

app/views/public_pages/show.html.haml
%h2 Donate To #{@page.name}
.charity
  %form#BB_BuyButtonForm{:action => "https://sandbox.google.com/checkout/cws/v2/Donations/#{@page.google_checkout_merchant_id}/checkoutForm", :method => "post", :name => "BB_BuyButtonForm", :onSubmit => "return validateAmount(this.item_price_1)", :target => "_top"}
    %fieldset
      %legend Donate To #{@page.name} Via Google Checkout
      %ol
        %li
          %input{:name => "item_name_1", :type => "hidden", :value => "Donation"}/
          %input{:name => "item_description_1", :type => "hidden", :value => "Donation to #{@page.name}"}/
          %input{:name => "item_quantity_1", :type => "hidden", :value => "1"}/
          %input{:name => "item_currency_1", :type => "hidden", :value => "USD"}/
          %input{:name => "item_is_modifiable_1", :type => "hidden", :value => "true"}/
          %input{:name => "item_min_price_1", :type => "hidden", :value => "0.01"}/
          %input{:name => "item_max_price_1", :type => "hidden", :value => "25000.0"}/
          %input{:name => "_charset_", :type => "hidden", :value => "utf-8"}/
          %input#item_price_1{:name => "item_price_1", :onfocus => "this.style.color='black'; this.value='';", :size => "11", :style => "color:grey;", :type => "text", :value => "Enter Amount"}/
          %input{:alt => "Donate", :src => "https://sandbox.google.com/checkout/buttons/donateNow.gif?merchant_id=#{@page.google_checkout_merchant_id}&w=115&h=50&style=trans&variant=text&loc=en_US", :type => "image"}/

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li= link_to "Sign out", destroy_user_session_path, :method => :delete
  %li= link_to "Settings", edit_user_registration_path
  %li= link_to 'Your charity pages', pages_path
- else
  %li= link_to "Sign up", new_user_registration_path
  %li= link_to "Sign in", new_user_session_path

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}